#!/bin/sh

#
# Check for pppd
if pidof pppd >/dev/null; then
        # Ok processes are running
        exit 0
fi

logger -t fix_inet "Restarting internet internet connection."

poff tkom >/dev/null || true

sleep 1

pon tkom
