#!/bin/sh
#
# Simple and stupid wrapper around dynamically generated VRF fix script.
# This wrapper will be run by at.
#
# Maximilian Wilhelm <max@sdn.clinic>
#  -- Tue, 28 Mar 2017 22:57:42 +0200
#

/usr/local/sbin/fix_ppp_vrf.gen
