#!/bin/sh

# Check if state-file exists, otherwise exit with unknown
if [ ! -f /var/cache/salt/state_apply ] ; then echo "Statefile does not exist" ; exit 3 ; fi

# Check age of statefile. If it's older than 2 hours, exit with unknown
if [ $(($(date +%s) - $(date -r /var/cache/salt/state_apply +%s))) -gt 25200 ] ; then echo "Statefile too old" ; exit 3 ; fi

# List all IDs and exclude ffho-repo
CHANGES_IDS=$(grep "ID:" /var/cache/salt/state_apply | grep -v "ID: .*-repo$")

if [ -n "$CHANGES_IDS" ] ; then
	echo "IDs with changes:"
	echo "$CHANGES_IDS"
	exit 1 # warning
fi

echo "Nothing to do"
exit 0 # ok

